### ISSUE TITLE
[Bug] Doesn't support auto updating through Prism Launcher

### ISSUE THREAD

**Issue by PlayfulPiano** [Stardust-Labs-MC/Structory#8]
### What Minecraft version(s) does this apply to?

1.20

### Project version

N/A

### Mod or datapack version?

Mod (Forge)

### Describe the bug

Both Structory and Structory Towers do not have the ability to be auto-updated using Prism. I believe the method to fix this is to enable 3rd party downloaders in cf settings of the project.

**Comment by catter1** [comment]
Nothing can be done about it for now. That is under Botany's control, and she has been (temporarily) away from the scene for several months. Last time I asked her about it (about 0.5 or 1 year ago?), she said it ws intentional, but don't remember the exact reasoning. Things have changed a lot since then, so when I am able to reach her again, it's one of the things I've been planning to ask her.

**Comment by PlayfulPiano** [comment]
Got it, thanks so much cat.
